### PR TITLE
startView mode functionality added

### PR DESCRIPTION
**Pull request by malliapi**

### CODE REVIEW

**Comment by malliapi** [comment]
Hi,

I am working on a project and would really love to use your code here but really need to have the startView mode functionality as per the original bootstrap datetimepicker. I have made the changes and I was wondering if you're happy to merge?

**Comment by malliapi** [comment]
Any news?

**Comment by chollier** [comment]
Hi,

Thanks for your contribution I'm definitely looking forward merging your PR. Only one thing : it seems like in the original datetimepicker, this option is named `viewMode`, would you mind renaming ?

**Comment by malliapi** [comment]
Many thanks for your reply. Would you mind reviewing once more? I have done the requested change

**Comment by chollier** [comment]
I just published v0.0.10 to npm

**Comment by mattdell** [comment]
Thanks for this. Excellent feature!

**Pull request merged**
