### PR TITLE
Minimum Date & Maximum Date Support

### PR DESCRIPTION
**Pull request by tewen**
### SUMMARY
- Added minDate prop and functionality to the calendar picker.
- Added maxDate prop and functionality to the calendar picker.

### DETAIL
- Updated the package.json to depend on the cjs build for DateTimeField.js.
- Added cjs, amd, and bower_components to .gitignore.
- setSelectedDate is now a noop for the disabled class case.
- Disabled classes are added to days that are before the minDate and after the maxDate.

### Improvements
- No handling for minDate and maxDate at the input level (our team is not using that at the moment). 
- minDate and maxDate are given as a moment object. Might be nice to include string parsing in the future.
- Checking if class is disabled in setSelectedDate is using a regex match, and would be better off with some of of lodash _.find method on the classList. This case will have matches for other classes with the word disabled in them, for now it was fine for our purposes.
- No handling for the time field as of yet (although not sure if it will be affected). Our team is also not using that.

### CODE REVIEW

**Comment by tewen** [comment]
@chollier We are going to use these features on our team, regardless. Hopefully it's a good starting point if you haven't worked with this feature just yet.

**Comment by chollier** [comment]
Hi @tewen 

First thanks for contributing !

What's the reason for renaming lib to cjs ? When I publish to npm I use the build-npm step first (see https://github.com/quri/react-bootstrap-datetimepicker/blob/master/package.json#L12) so that the JSX files get converted to actual ES5 files in the lib folder and then I push to the npm repository. I'll add a BUILD information to the README. 

Also the AMD build is already in /dist (see https://github.com/quri/react-bootstrap-datetimepicker/blob/master/webpack.config.js#L26) thanks to webpack and the UMD flag (see http://webpack.github.io/docs/configuration.html#output-librarytarget). I use npm run build && npm run build-min before releasing new version (https://github.com/quri/react-bootstrap-datetimepicker/blob/master/package.json#L13-L14)

**Comment by tewen** [comment]
Hey @chollier I can keep it back at lib if you like. That was for the sake of my team, and the fact that we needed to bull it directly from the repository. Didn't know much about the npm build piece. 

I will switch that at some point in the next day or so.

**Comment by chollier** [comment]
Hey I did a few changes, added an example and merged your PR :) thanks !

**Pull request merged**
