### PR TITLE
state for inputValue is already defaulted correctly and does not need…

### PR DESCRIPTION
**Pull request by theresakhoo**
… to get dateTime.

My use case is as follows

I have 2 datepickers on the same page.  They default to defaultText = 'Select date.'
If I change the date for the first date picker, the 2nd will show today's date instead of continuing to show 'Select date.'  This pull request fixes that.

Thanks,
Theresa

### CODE REVIEW

**Comment by chollier** [comment]
If your 2 datepicker's props depend on different props / state using one shouldn't impact the other one. I think your issue is that they are couple.

Also by removing the line you're removing, what happens when an higher order component of the DateTimeField changes it's `dateTime` prop ? Then the input wouldn't get updated.

**Comment by theresakhoo** [comment]
I have modified the example to show the use case.

I think two things that are confusing are
- if defaultText is defined, then if a date is not selected, shouldn't defaultText take precedence over dateTime
- because dateTime has a default value (ie moment().format("x")), then you can't really tell if it was empty or not

**Comment by chollier** [comment]
> If you select a date in the first date picker, then the second will show today's date.

Hrmm, I just loaded your PR, ran `npm run examples`  and I don't get that behavior : https://www.dropbox.com/s/nupzqetkbyl154b/PR87.mov?dl=0

also I slighlty modified the code and added a test that shows why updating inputValue on componentWillReceiveProps is important : https://github.com/quri/react-bootstrap-datetimepicker/commit/8468f024922ccfc20ef491e50a67b8e045ae756a

**Comment by chollier** [comment]
I can see where you're coming from regarding the confusing part though, that's a reason why i'm trying to slowly add tests and enhance documentation so that we can spot check the expected behavior.

**Comment by theresakhoo** [comment]
In my PR, it also includes the fix, so you won't see the behavior I described (my bad).  

Just take out the following line from componentsWillReceiveProps, or I can update the PR if you prefer.
inputValue: moment(nextProps.dateTime, nextProps.format, true).format(nextProps.inputFormat)

I agree and appreciate your comment on tests and docs.  Your test should work with my change as well.

**Comment by theresakhoo** [comment]
I'm closing this PR, and creating a new one with a test to demonstrate the issue.

**Pull request closed without merging**
