### PR TITLE
Passed the event object as second argument in all onChange calls #42

### PR DESCRIPTION
**Pull request by petesaia**
#42

You should re-run the webpack/minification in your environment because I wasn't able to create the minified version for some reason.

### CODE REVIEW

**Comment by chollier** [comment]
I only run webpack build when bumping version anyway ;-)

I would be curious to see this working and integrated with newform! Out of curiosity what's the purpose of bubbling up the event ?

**Comment by fcm10101** [comment]
I want to run the example, but there is an error

**Comment by chollier** [comment]
Can you maybe elaborate? Context ? Stack trace?



—

**Comment by petesaia** [comment]
If you're familiar with newforms I'd love to hear your advice or an alternative solution. I'm relatively new to the library.

I'm implementing this as a Widget. This widget can be added to either `DateInput` or `DateTimeInput` like so:

```javascript
  some_date_field: forms.DateField({
    required: true,
    label: 'Employment Date',
    widget: DateTimePickerInput,
    widgetAttrs: {
       onlyDate: true
    }
  }),
```

bootstrap-datetimepicker is already using `onChange` on the input so I basically need to extend that by doing a little trickery - saving `BoundField`'s `onChange` from kwargs to a variable, removing it (`let orgOnChange = finalAttrs.onChange;`), and then calling it manually from within a local `onChange` that's interfacing with the datetimepicker (which is currently only supplying the value). Basically, relaying the call as if it was actually on the input.

You'll notice I'm using the boolean `onlyDate` to determine what format it display. This serves my purposes well for this application but if there is interest in open sourcing the implementation I'd probably make properties to provide a custom format.

Here is the full widget below:

```javascript
/**
 * @module app/components/newforms/Widget/DateTimePickerInput
 */
import React from 'react';
import forms from 'newforms';
import DateTimeField from 'react-bootstrap-datetimepicker';

/**
 * Widget to extend.
 * @constructor
 * @type {function}
 */
const DateTimeBaseInput = forms.DateTimeBaseInput;

/**
 * Creates a custom Bootstrap DateTimePicker widget.
 *
 * Both format and inputFormat should be provided as newform's datepicker and
 * bootstrap's datepicker require a different format.
 *
 * @constructor
 * @extends DateTimeBaseInput
 * @type {function}
 */
const DateTimePickerInput = DateTimeBaseInput.extend({
  constructor: function DateTimePickerInput(kwargs) {
    if (!(this instanceof DateTimePickerInput)) {
      return new DateTimePickerInput(kwargs);
    }
    DateTimeBaseInput.call(this, kwargs);
  },

  /**
   * Create the element.
   * @see { @link: http://momentjs.com/docs/#/displaying/format/ } }
   * @see { @link: https://github.com/insin/isomorph#formatting-directives } }
   */
  render: function(name, value, kwargs) {
    let finalAttrs = this.buildAttrs(kwargs.attrs, {
      type: this.inputType,
      name: name,
      dateTime: value || Date.now().toString()
    });

    // Save the onChange from the BoundField.
    let orgOnChange = finalAttrs.onChange;

    // Use on change from DateTimeField and then manually call newform's.
    var onChange: function(timestamp, event) {
      // orgOnChange(event); // This needs to be the react event!
    };

    delete finalAttrs.onChange; // Remove the newforms onChange for now.

    if (this.attrs.onlyDate) {
      this.formatType = 'DATE_INPUT_FORMATS';
      this.format = '%m/%d/%y';
      finalAttrs.inputFormat = 'MM/DD/YY';
    } else {
      this.formatType = 'DATETIME_INPUT_FORMATS';
      this.format = '%m/%d/%y %I:%M %p';
      finalAttrs.inputFormat = 'MM/DD/YY h:mm A';
    }

    return <DateTimeField defaultText='No date selected.' onChange={onChange} inputFormat={finalAttrs.inputFormat} dateTime={inputProps}/>;
  }
});

export default DateTimePickerInput;
```

**Comment by petesaia** [comment]
Any thoughts on this, @chollier?

**Comment by chollier** [comment]
Ok I got it, it's a little bit weird to me that this *has* to be a react event but I can understand. 

Would you mind unchecking the changes to the compiled files from your pull-request ? I only do that when bumping versions

**Comment by petesaia** [comment]
It's very weird to me too. I believe because newforms was ported over and not built specifically with React in mind. It's one of a few things I found to be pretty odd with that library, actually. I ended up writing a form module [here](https://github.com/LevInteractive/react-serial-forms) which we'll be using. Feel free not to cancel this merge request unless you want to expose the synthetic event, but I won't be needing it anymore.

**Pull request closed without merging**
