### PR TITLE
Free input value #2

### PR DESCRIPTION
**Pull request by chollier**

### CODE REVIEW

**Comment by chollier** [comment]
also I noticed @joshcarr had that figured out in his branch, maybe I could cherry-pick some commits

**Comment by joshcarr** [comment]
I've been meaning to clean my work up and make a pull request. Please advise on what aspect you'd like to see merged into this?

**Comment by chollier** [comment]
I like that you removed the dependency of react-bootstrap, even though I always intended to use it in parallel, removing this dependency feels right.

I like that you added another example that shows how to use onChange. I would maybe rename it though.

I also like https://github.com/joshcarr/react-bootstrap-datetimepicker/blob/master/src/DateTimeField.jsx#L20-L22 (as well as modifications in the doc)

Not a huge fan of https://github.com/joshcarr/react-bootstrap-datetimepicker/blob/master/src/DateTimeField.jsx#L47 I'd rather have the input having `value={this.state.inputValue}`

I would move https://github.com/joshcarr/react-bootstrap-datetimepicker/blob/master/src/DateTimeField.jsx#L68 in the setState callback only if the format inputted is valid (I don't see a reason to call handleChange if the date inputted isn't valid)

I'm also not a huge fan of using ReactLink in general

**Comment by malliapi** [comment]
@chollier indeed the code works well but in regards to https://github.com/joshcarr/react-bootstrap-datetimepicker/blob/master/src/DateTimeField.jsx#L68 , what if the intended project is attempting to use a validation framework on top of this component, I see a reason to call the handleChange otherwise we would swallow the custom error message that a project might be attempting to implement? What do you think?

**Comment by malliapi** [comment]
Any news?

**Comment by malliapi** [comment]
@chollier Sorry to bother you again but its a bit urgent to get it in to the project. Would you have a minute to see if you are happy to merge?

**Comment by chollier** [comment]
Hey @malliapi sorry I've been pretty busy recently. I plan on merging this early this week. Sorry for the delays :)

**Pull request closed without merging**
